<a href="https://colab.research.google.com/github/rachit44/my_AI_journey/blob/main/module-0-numpy-pandas/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np

https://pandas.pydata.org/docs/user_guide/10min.html REFERENCE

In [7]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])

In [8]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [9]:
dates = pd.date_range("20130101", periods=6)

In [10]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01  0.784151  1.507128  1.226488 -0.500217
2013-01-02 -0.641087  1.355360  0.074623  0.208832
2013-01-03 -1.036224  0.040582  0.225198 -0.072808
2013-01-04 -0.340017 -0.310209 -0.110955  0.157236
2013-01-05 -1.555806  0.402885  1.412489  0.179606
2013-01-06 -0.093150  0.443409  0.040704  1.948874

In [11]:
df[:2][:3]

                   A         B         C         D
2013-01-01  0.784151  1.507128  1.226488 -0.500217
2013-01-02 -0.641087  1.355360  0.074623  0.208832