<a href="https://colab.research.google.com/github/rachit44/my_AI_journey/blob/main/module-0-numpy-pandas/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
import numpy as np

https://pandas.pydata.org/docs/user_guide/10min.html REFERENCE

In [20]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])

In [21]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [22]:
dates = pd.date_range("20130101", periods=6)

In [23]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01  0.110910 -0.632907  1.737445  0.931309
2013-01-02 -0.518300 -1.030761 -0.505291  0.735447
2013-01-03  0.701362 -0.331075 -0.095039 -0.073328
2013-01-04 -0.524884  0.983164  1.012707 -1.685757
2013-01-05  1.021688 -0.569969 -1.483584 -1.205099
2013-01-06 -0.300057 -1.668523  2.552017  0.858666

In [24]:
df[:2][:3]

                  A         B         C         D
2013-01-01  0.11091 -0.632907  1.737445  0.931309
2013-01-02 -0.51830 -1.030761 -0.505291  0.735447

In [25]:
df.add(df)

                   A         B         C         D
2013-01-01  0.221821 -1.265814  3.474890  1.862619
2013-01-02 -1.036599 -2.061522 -1.010581  1.470894
2013-01-03  1.402725 -0.662150 -0.190077 -0.146656
2013-01-04 -1.049768  1.966327  2.025414 -3.371514
2013-01-05  2.043377 -1.139938 -2.967169 -2.410198
2013-01-06 -0.600114 -3.337047  5.104033  1.717332