<a href="https://colab.research.google.com/github/rachit44/my_AI_journey/blob/main/module-0-numpy-pandas/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

https://pandas.pydata.org/docs/user_guide/10min.html REFERENCE

In [2]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])

In [3]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [4]:
dates = pd.date_range("20130101", periods=6)

In [5]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01 -0.547799  1.505268  0.638952  2.697030
2013-01-02 -0.149121  1.030874  0.352997  0.169472
2013-01-03  2.429607 -0.560731 -0.699292  0.821671
2013-01-04  1.215771  0.640715  0.259536  0.695693
2013-01-05  1.104928  0.290339 -0.334350  0.206904
2013-01-06 -0.142586  0.633124 -0.752940 -1.355871