<a href="https://colab.research.google.com/github/rachit44/my_AI_journey/blob/main/module-0-numpy-pandas/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

https://pandas.pydata.org/docs/user_guide/10min.html REFERENCE

In [5]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])

In [6]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [8]:
dates = pd.date_range("20130101", periods=6)

In [11]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01 -0.072001  0.109308 -0.017523  0.525272
2013-01-02 -1.472886 -0.126588  0.229587 -0.204624
2013-01-03  0.113624 -0.345085  0.507874  1.104118
2013-01-04  0.045938 -1.222080 -1.227829 -0.360353
2013-01-05 -1.403214  1.276499 -1.452893  0.729973
2013-01-06 -0.412396 -0.354039 -0.528411  1.048937